apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: otckeypairs.otckeypair.ansible-otc.net
spec:
  group: otckeypair.ansible-otc.net
  names:
    kind: OtcKeypair
    listKind: OtcKeypairList
    plural: otckeypairs
    singular: otckeypair
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1
    served: true
    storage: true
