apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: otceips.otceip.ansible-otc.net
spec:
  group: otceip.ansible-otc.net
  names:
    kind: OtcEip
    listKind: OtcEipList
    plural: otceips
    singular: otceip
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1
    served: true
    storage: true
