apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: otcrdsses.otcrds.ansible-otc.net
spec:
  group: otcrds.ansible-otc.net
  names:
    kind: OtcRds
    listKind: OtcRdsList
    plural: otcrdsses
    singular: otcrds
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1
    served: true
    storage: true
