apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: otcvpcs.otcecs.ansible-otc.net
spec:
  group: otcvpc.ansible-otc.net
  names:
    kind: OtcVpc
    listKind: OtcVpcList
    plural: otcvpcs
    singular: otcvpc
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1
    served: true
    storage: true
