apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: otcsubnets.otcsubnet.ansible-otc.net
spec:
  group: otcsubnet.ansible-otc.net
  names:
    kind: OtcSubnet
    listKind: OtcSubnetList
    plural: otcsubnets
    singular: otcsubnet
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1
    served: true
    storage: true
