apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: otcsecgroups.otcecs.ansible-otc.net
spec:
  group: otcsecgroup.ansible-otc.net
  names:
    kind: OtcSecgroup
    listKind: OtcSecgroupList
    plural: otcsecgroups
    singular: otcsecgroup
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1
    served: true
    storage: true
