apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: otcecs.ansible-otc.net
spec:
  group: ansible-otc.net
  names:
    kind: OtcEcs
    listKind: OtcEcsList
    plural: otcecs
    singular: otcecs
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1
    served: true
    storage: true
