---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ansible-otc-operator-subnet
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ansible-otc-operator-subnet
  template:
    metadata:
      labels:
        name: ansible-otc-operator-subnet
    spec:
      serviceAccountName: ansible-otc-operator
      containers:
        - name: ansible-otc-operator-subnet
          image: "eumel8/ansible-otc-operator-subnet"
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          - name: key-file
            mountPath: "/key-file"
            readOnly: true
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ansible-otc-operator-subnet"
            - name: ANSIBLE_GATHERING
              value: explicit
            - name: OS_PROJECT_NAME
              valueFrom:
                secretKeyRef:
                  name: cloud-credentials
                  key: OS_PROJECT_NAME
            - name: OS_REGION_NAME
              valueFrom:
                secretKeyRef:
                  name: cloud-credentials
                  key: OS_REGION_NAME
            - name: OS_AUTH_URL
              valueFrom:
                secretKeyRef:
                  name: cloud-credentials
                  key: OS_AUTH_URL
            - name: OS_IDENTITY_API_VERSION
              valueFrom:
                secretKeyRef:
                  name: cloud-credentials
                  key: OS_IDENTITY_API_VERSION
            - name: OS_USER_DOMAIN_NAME
              valueFrom:
                secretKeyRef:
                  name: cloud-credentials
                  key: OS_USER_DOMAIN_NAME
            - name: OS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cloud-credentials
                  key: OS_USERNAME
            - name: OS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloud-credentials
                  key: OS_PASSWORD
      volumes:
        - name: runner
          emptyDir: {}
        - name: key-file
          secret:
            secretName: key-file
